// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
// Storage configuration
export const STORAGE_CONFIG = {
  accessKeyId: import.meta.env.VITE_SUPABASE_STORAGE_ACCESS_KEY_ID,
  secretAccessKey: import.meta.env.VITE_SUPABASE_STORAGE_SECRET_ACCESS_KEY,
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
