// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpfyejxokywdkudkeywv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZnllanhva3l3ZGt1ZGtleXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTU1ODQsImV4cCI6MjA2NjI5MTU4NH0.MvgGO6iVBqvn25oVptUHigaxVBTeezpR69wpEld3kLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);